import { Slug, SanityImageMetadata, Product } from "@/sanity.types";
import { imageUrl } from "@/sanity/lib/imageUrl";
import Image from "next/image";
import Link from "next/link";
import styles from "./ProductThumb.module.css";
import { ImageType } from "../types";

// This is manually typed (based on Product type, simplified), as nested types are not automatically generated by the Sanity Schema extraction
type ProductWithGallery = {
  name?: string;
  slug?: Slug;
  imageGallery?: ImageType[];
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    _type: "block";
  }>;
  price?: number;
};

const ProductThumb = ({
  product,
  isPreloaded = false,
}: {
  product: ProductWithGallery;
  isPreloaded?: boolean;
}) => {
  return (
    // Accessible card: https://inclusive-components.design/cards/#thepseudocontenttrick
    <li className={styles.Card}>
      {product.imageGallery && (
        <div className={styles.Card_image}>
          <Image
            src={`${imageUrl(product.imageGallery[0]).url()}`}
            alt=""
            fill
            sizes="(max-width: 480px) 100vw, (max-width: 800px) 50vw, 33vw"
            // Image loading optimizations
            priority={isPreloaded}
            placeholder="blur"
            blurDataURL={`${product.imageGallery[0] && product.imageGallery[0].asset?.metadata?.lqip}`}
          />
        </div>
      )}
      <div className={styles.Card_textWrapper}>
        <div>
          <h2>
            <Link
              className={styles.Card_link}
              href={`/product/${product.slug?.current}`}
            >
              {product.name}
            </Link>
          </h2>
          <p className={styles.Card_description}>
            {product.description
              ?.map((block) =>
                block._type == "block"
                  ? block.children?.map((child) => child.text).join("")
                  : ""
              )
              .join(" ")
              .slice(0, 100) || "No description available"}
          </p>
        </div>
        <p className={styles.Card_price}>€ {product.price?.toFixed(2)}</p>
      </div>
    </li>
  );
};

export default ProductThumb;
