import { SanityImageMetadata } from "@/sanity.types";

// CART CONTEXT

export type CartItem = {
  _id: string;
  name: string;
  price: number;
  slug: string;
  image: string;
  description: string;
};

export type CartState = {
  cartItems: CartItem[];
};

// SANITY, manually set types
// Based on imageGallery type, simplified — as nested types are not automatically generated by the Sanity Schema extraction
export type ImageType = {
  _key: string;
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    metadata?: SanityImageMetadata;
  };
};
